force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Desired_Job__c.field-meta.xml
<CustomField>
    <fullName>Desired_Job__c</fullName>
    <label>Desired Job</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Cybersecurity Analyst</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Experience_Level__c.field-meta.xml
<CustomField>
    <fullName>Experience_Level__c</fullName>
    <label>Experience Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internship</fullName>
            </value>
            <value>
                <fullName>Entry</fullName>
            </value>
            <value>
                <fullName>Mid</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Open_To_Remote_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Open_To_Remote_Jobs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open To Remote Jobs?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Experience_Level__c.field-meta.xml
<CustomField>
    <fullName>Experience_Level__c</fullName>
    <label>Experience Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entry</fullName>
            </value>
            <value>
                <fullName>Mid</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Remote__c.field-meta.xml
<CustomField>
    <fullName>Remote__c</fullName>
    <label>Remote?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Cybersecurity Analyst</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/JobTriggerHandler.cls
public with sharing class JobTriggerHandler {
    public static void handleAfterInsertOrUpdate(List<Job__c> jobs) {

        List<Candidate__c> candidates = [SELECT Id,Location__c,Desired_Job__c,Experience_Level__c,Open_To_Remote_Jobs__c FROM Candidate__c];

        Map<String, List<Candidate__c>> candidatesByKey = new Map<String, List<Candidate__c>>();

        for(Candidate__c candidate : candidates) {
            String locationKey = candidate.Open_To_Remote_Jobs__c != 'Yes' ? candidate.Location__c : 'Yes';
            String candidateKey = (candidate.Desired_Job__c + '|' + candidate.Experience_Level__c + '|' + locationKey);
            if (!candidatesByKey.containsKey(candidateKey)) {
                candidatesByKey.put(candidateKey, new List<Candidate__c>());
            }
            candidatesByKey.get(candidateKey).add(candidate);
        }

        Set<Id> jobIds = new Set<Id>();
        Set<Id> candidateIds = new Set<Id>();


        for(List<Candidate__c> candidateList : candidatesByKey.values()) {
            for(Candidate__c candidate : candidateList) {
                candidateIds.add(candidate.Id);
            }
        }

        for (Job__c job : jobs) {
            jobIds.add(job.Id);
        }

        List<Match__c> existingMatches = [
            SELECT Job__c,Candidate__c 
            FROM Match__c WHERE Job__c 
            IN :jobIds 
            AND Candidate__c IN :candidateIds
        ];
        Set<String> existingMatchesKeys = new Set<String>();
        for(Match__c match : existingMatches) {
            String key = (match.Job__c + '|' + match.Candidate__c);
            existingMatchesKeys.add(key);
        }

        List<Match__c> matchesToInsert = new List<Match__c>();
        for (Job__c job : jobs) {
            String locationKey = job.Remote__c != 'Yes' ? job.Location__c : 'Yes';
            
            String jobKey = (job.Title__c + '|' + job.Experience_Level__c + '|' + locationKey);

            if(candidatesByKey.containsKey(jobKey)) {
                
                for(Candidate__c candidate : candidatesByKey.get(jobKey)) {
                    String matchKey = (job.Id + '|' + candidate.Id);
                    if(!existingMatchesKeys.contains(matchKey)) {
                    Match__c match = new Match__c();
                    match.Job__c = job.Id;
                    match.Candidate__c = candidate.Id;
                    match.Status__c = 'New';
                    match.Score__c = 100;
                    matchesToInsert.add(match);
                    }
                }
            }
        }

        if(!matchesToInsert.isEmpty()) {
            insert matchesToInsert;
        }
    }
}