force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Experience_Level__c.field-meta.xml
<CustomField>
    <fullName>Experience_Level__c</fullName>
    <label>Experience Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internship</fullName>
            </value>
            <value>
                <fullName>Entry</fullName>
            </value>
            <value>
                <fullName>Mid</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Is_Remote__c.field-meta.xml
<CustomField>
    <fullName>Is_Remote__c</fullName>
    <label>Open to Remote?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Desired Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Cybersecurity Analyst</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Resume_URL__c.field-meta.xml
<CustomField>
    <fullName>Resume_URL__c</fullName>
    <label>Resume URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <description>Skills that the candidate possesses, selected from a predefined list.</description>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Aura Components</fullName>
            </value>
            <value>
                <fullName>Flows</fullName>
            </value>
            <value>
                <fullName>Permission Sets</fullName>
            </value>
            <value>
                <fullName>Reports and Dashboards</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Data Loader</fullName>
            </value>
            <value>
                <fullName>User Stories</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Agile Methodology</fullName>
            </value>
            <value>
                <fullName>Data Mapping</fullName>
            </value>
            <value>
                <fullName>Use Cases</fullName>
            </value>
            <value>
                <fullName>Wireframing</fullName>
            </value>
            <value>
                <fullName>Figma</fullName>
            </value>
            <value>
                <fullName>Design Tokens</fullName>
            </value>
            <value>
                <fullName>UX Writing</fullName>
            </value>
            <value>
                <fullName>Design System</fullName>
            </value>
            <value>
                <fullName>Security Review</fullName>
            </value>
            <value>
                <fullName>Integration Patterns</fullName>
            </value>
            <value>
                <fullName>Multi-Org Strategy</fullName>
            </value>
            <value>
                <fullName>System Scalability</fullName>
            </value>
            <value>
                <fullName>Data Modeling</fullName>
            </value>
            <value>
                <fullName>Shield Encryption</fullName>
            </value>
            <value>
                <fullName>Field Level Security</fullName>
            </value>
            <value>
                <fullName>Event Monitoring</fullName>
            </value>
            <value>
                <fullName>Audit Trail</fullName>
            </value>
            <value>
                <fullName>User Authentication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Experience_Level__c.field-meta.xml
<CustomField>
    <fullName>Experience_Level__c</fullName>
    <label>Experience Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entry</fullName>
            </value>
            <value>
                <fullName>Mid</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Is_Remote__c.field-meta.xml
<CustomField>
    <fullName>Is_Remote__c</fullName>
    <label>Remote?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Offered_Salary__c.field-meta.xml
<CustomField>
    <fullName>Offered_Salary__c</fullName>
    <label>Offered Salary</label>
    <precision>10</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Business Analyst</fullName>
            </value>
            <value>
                <fullName>Salesforce Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Cybersecurity Analyst</fullName>
            </value>
            <value>
                <fullName>Salesforce Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>Skills that the job possesses, selected from a predefinedlist.</description>
    <label>Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Aura Components</fullName>
            </value>
            <value>
                <fullName>Flows</fullName>
            </value>
            <value>
                <fullName>Permission Sets</fullName>
            </value>
            <value>
                <fullName>Reports and Dashboards</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Data Loader</fullName>
            </value>
            <value>
                <fullName>User Stories</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Agile Methodology</fullName>
            </value>
            <value>
                <fullName>Data Mapping</fullName>
            </value>
            <value>
                <fullName>Use Cases</fullName>
            </value>
            <value>
                <fullName>Wireframing</fullName>
            </value>
            <value>
                <fullName>Figma</fullName>
            </value>
            <value>
                <fullName>Design Tokens</fullName>
            </value>
            <value>
                <fullName>UX Writing</fullName>
            </value>
            <value>
                <fullName>Design System</fullName>
            </value>
            <value>
                <fullName>Security Review</fullName>
            </value>
            <value>
                <fullName>Integration Patterns</fullName>
            </value>
            <value>
                <fullName>Multi-Org Strategy</fullName>
            </value>
            <value>
                <fullName>System Scalability</fullName>
            </value>
            <value>
                <fullName>Data Modeling</fullName>
            </value>
            <value>
                <fullName>Shield Encryption</fullName>
            </value>
            <value>
                <fullName>Field Level Security</fullName>
            </value>
            <value>
                <fullName>Event Monitoring</fullName>
            </value>
            <value>
                <fullName>Audit Trail</fullName>
            </value>
            <value>
                <fullName>User Authentication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/JobCandidateUniqueKey__c.field-meta.xml
<CustomField>
    <fullName>JobCandidateUniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>JobCandidateUniqueKey</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Match__c/fields/Status_Match__c.field-meta.xml
<CustomField>
    <fullName>Status_Match__c</fullName>
    <label>Status Match</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Handler_JobTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_Handler_JobTrigger {

    @isTest
    static void newJobAdded() {
        Candidate__c testCandidate = new Candidate__c();
        testCandidate.Position__c = 'Salesforce Developer';
        testCandidate.Location__c = 'San Francisco';
        testCandidate.First_Name__c = 'John';
        testCandidate.Last_Name__c = 'Doe';
        testCandidate.Email__c = 'test@test.com';
        testCandidate.Experience_Level__c = 'Mid';
        testCandidate.Resume_URL__c = 'http://example.com/resume.pdf';
        testCandidate.Skills__c = 'Apex;LWC;Visualforce;SOQL;Aura Components';
        testCandidate.Is_Remote__c = 'Yes';
        insert testCandidate;

        Job__c testJob = new Job__c();
        testJob.Position__c = 'Salesforce Developer';
        testJob.Company__c = 'Test Company';
        testJob.Location__c = 'San Francisco';
        testJob.Skills__c = 'Apex;LWC;Visualforce;SOQL;HTML';
        testJob.Offered_Salary__c = 120000;
        testJob.Is_Remote__c = 'Yes';
        testJob.Experience_Level__c = 'Mid';

        test.startTest();
        insert testJob;
        test.stopTest();

        String expectedKey = testJob.Id + '|' + testCandidate.Id;

        List<Match__c> result = [SELECT Id, Job__c, Candidate__c, Status_Match__c, Match_Score__c, JobCandidateUniqueKey__c
                                  FROM Match__c 
                                  WHERE JobCandidateUniqueKey__c = :expectedKey];
        
        System.assertEquals(1, result.size(), 'Expected one match to be created');
        System.assertEquals('New', result[0].Status_Match__c, 'Expected status match');
        System.assertEquals(80, result[0].Match_Score__c, 'Expected match score');
    }

    @isTest
    static void noMatchFound() {
        Candidate__c testCandidate = new Candidate__c();
        testCandidate.Position__c = 'Salesforce Developer';
        testCandidate.Location__c = 'San Francisco';
        testCandidate.First_Name__c = 'John';
        testCandidate.Last_Name__c = 'Doe';
        testCandidate.Email__c = 'test@test.com';
        testCandidate.Experience_Level__c = 'Mid';
        testCandidate.Resume_URL__c = 'http://example.com/resume.pdf';
        testCandidate.Skills__c = 'Apex;LWC;Visualforce;SOQL;Aura Components';
        testCandidate.Is_Remote__c = 'Yes';
        insert testCandidate;

        Job__c testJob = new Job__c();
        testJob.Position__c = 'Salesforce Administrator';
        testJob.Company__c = 'Test Company';
        testJob.Location__c = 'San Francisco';
        testJob.Skills__c = 'Flows;Permission Sets;Reports and Dashboards;Process Builder;Data Loader';
        testJob.Offered_Salary__c = 120000;
        testJob.Is_Remote__c = 'Yes';
        testJob.Experience_Level__c = 'Mid';

        test.startTest();
        insert testJob;
        test.stopTest();

        String expectedKey = testJob.Id + '|' + testCandidate.Id;

        List<Match__c> result = [SELECT Id, Job__c, Candidate__c, Status_Match__c, Match_Score__c, JobCandidateUniqueKey__c 
                                  FROM Match__c 
                                  WHERE JobCandidateUniqueKey__c = :expectedKey];
        
        System.assertEquals(0, result.size(), 'No match must be created');
    }

    @isTest
    static void noDuplicatedMatch() {

        Candidate__c testCandidate = new Candidate__c();
        testCandidate.Position__c = 'Salesforce Developer';
        testCandidate.Location__c = 'San Francisco';
        testCandidate.First_Name__c = 'John';
        testCandidate.Last_Name__c = 'Doe';
        testCandidate.Email__c = 'test@test.com';
        testCandidate.Experience_Level__c = 'Mid';
        testCandidate.Resume_URL__c = 'http://example.com/resume.pdf';
        testCandidate.Skills__c = 'Apex;LWC;Visualforce;SOQL;Aura Components';
        testCandidate.Is_Remote__c = 'Yes';
        insert testCandidate;

        Job__c testJob = new Job__c();
        testJob.Position__c = 'Salesforce Developer';
        testJob.Company__c = 'Test Company';
        testJob.Location__c = 'San Francisco';
        testJob.Skills__c = 'Apex;LWC;Visualforce;SOQL;HTML';
        testJob.Offered_Salary__c = 120000;
        testJob.Is_Remote__c = 'Yes';
        testJob.Experience_Level__c = 'Mid';
        insert testJob;

        test.startTest();
        testJob.Offered_Salary__c = 150000;
        update testJob;
        test.stopTest();

        List<Match__c> result = [SELECT Id, Job__c, Candidate__c, Status_Match__c, Match_Score__c 
                                  FROM Match__c 
                                  WHERE Job__c = :testJob.Id AND Candidate__c = :testCandidate.Id
                                  ];
        
        System.assertEquals(1, result.size(), 'Expected no duplicated match to be created');
    }
}