force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Experience_Level__c.field-meta.xml
<CustomField>
    <fullName>Experience_Level__c</fullName>
    <label>Experience Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internship</fullName>
            </value>
            <value>
                <fullName>Entry</fullName>
            </value>
            <value>
                <fullName>Mid</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Is_Remote__c.field-meta.xml
<CustomField>
    <fullName>Is_Remote__c</fullName>
    <label>Open to Remote?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Desired Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Cybersecurity Analyst</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Experience_Level__c.field-meta.xml
<CustomField>
    <fullName>Experience_Level__c</fullName>
    <label>Experience Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entry</fullName>
            </value>
            <value>
                <fullName>Mid</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Is_Remote__c.field-meta.xml
<CustomField>
    <fullName>Is_Remote__c</fullName>
    <label>Remote?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Business Analyst</fullName>
            </value>
            <value>
                <fullName>Salesforce Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Cybersecurity Analyst</fullName>
            </value>
            <value>
                <fullName>Salesforce Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/JobCandidateUniqueKey__c.field-meta.xml
<CustomField>
    <fullName>JobCandidateUniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>JobCandidateUniqueKey</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Match__c/fields/Status_Match__c.field-meta.xml
<CustomField>
    <fullName>Status_Match__c</fullName>
    <label>Status Match</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Handler_JobTrigger.cls
public with sharing class Handler_JobTrigger {
    public class TriggerContext {
        public Boolean isAfter;
        public Boolean isInsert;
        public Boolean isUpdate;

        public TriggerContext(Boolean isAfter, Boolean isInsert, Boolean isUpdate) {
            this.isAfter = isAfter;
            this.isInsert = isInsert;
            this.isUpdate = isUpdate;
        }
    }

    private static Map<String, List<Candidate__c>> groupCandidatesByKey(List<Candidate__c> candidates) {
        Map<String, List<Candidate__c>> candidatesByKey = new Map<String, List<Candidate__c>>();

        for(Candidate__c candidate : candidates) {
            String locationKey = String.valueOf(candidate.Is_Remote__c) == 'Yes' ? 'YesToRemote' : candidate.Location__c;
            String candidateKey = (candidate.Position__c + '|' + candidate.Experience_Level__c + '|' + locationKey);
            if (!candidatesByKey.containsKey(candidateKey)) {
                candidatesByKey.put(candidateKey, new List<Candidate__c>());
            }
            candidatesByKey.get(candidateKey).add(candidate);
        }
        return candidatesByKey;
    }

    private static List<Match__c> buildMatchesToInsert(List<Job__c> jobs, Map<String, List<Candidate__c>> candidatesByKey) {
        List<Match__c> matchesToInsert = new List<Match__c>();

        for (Job__c job : jobs) {
            String locationKey = String.valueOf(job.Is_Remote__c) == 'Yes' ? 'YesToRemote' : job.Location__c;
            String jobKey = (job.Position__c + '|' + job.Experience_Level__c + '|' + locationKey);

            if(candidatesByKey.containsKey(jobKey)) {
                
                for(Candidate__c candidate : candidatesByKey.get(jobKey)) {
                    Match__c match = new Match__c();
                    match.Job__c = job.Id;
                    match.Candidate__c = candidate.Id;
                    match.Status_Match__c = 'New';
                    match.Match_Score__c = Service_MatchScoring.calculateScore(job, candidate).score; //Calculo de match score
                    match.JobCandidateUniqueKey__c = job.Id + '|' + candidate.Id;
                    matchesToInsert.add(match);
                }
            }
        }

        return matchesToInsert;
    }

    public static void handleAfterInsertOrUpdate(List<Job__c> jobs, TriggerContext context) {
        if (!context.isAfter || (!context.isInsert && !context.isUpdate)) {
            return;
        }

        List<Candidate__c> candidates = Service_FetchCandidates.getCandidates();

        Map<String, List<Candidate__c>> candidatesByKey = groupCandidatesByKey(candidates);

        List<Match__c> matchesToInsert = buildMatchesToInsert(jobs, candidatesByKey);

        if(!matchesToInsert.isEmpty()) {
            try {
                Util_Security.checkCreateAccess('Match__c');
                insert matchesToInsert;
            } catch (Exception e) {
                System.debug('Error while inserting match: ' + e.getMessage());
            }
        }
    }
}