force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <description>Skills that the candidate possesses, selected from a predefined list.</description>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Aura Components</fullName>
            </value>
            <value>
                <fullName>Flows</fullName>
            </value>
            <value>
                <fullName>Permission Sets</fullName>
            </value>
            <value>
                <fullName>Reports and Dashboards</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Data Loader</fullName>
            </value>
            <value>
                <fullName>User Stories</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Agile Methodology</fullName>
            </value>
            <value>
                <fullName>Data Mapping</fullName>
            </value>
            <value>
                <fullName>Use Cases</fullName>
            </value>
            <value>
                <fullName>Wireframing</fullName>
            </value>
            <value>
                <fullName>Figma</fullName>
            </value>
            <value>
                <fullName>Design Tokens</fullName>
            </value>
            <value>
                <fullName>UX Writing</fullName>
            </value>
            <value>
                <fullName>Design System</fullName>
            </value>
            <value>
                <fullName>Security Review</fullName>
            </value>
            <value>
                <fullName>Integration Patterns</fullName>
            </value>
            <value>
                <fullName>Multi-Org Strategy</fullName>
            </value>
            <value>
                <fullName>System Scalability</fullName>
            </value>
            <value>
                <fullName>Data Modeling</fullName>
            </value>
            <value>
                <fullName>Shield Encryption</fullName>
            </value>
            <value>
                <fullName>Field Level Security</fullName>
            </value>
            <value>
                <fullName>Event Monitoring</fullName>
            </value>
            <value>
                <fullName>Audit Trail</fullName>
            </value>
            <value>
                <fullName>User Authentication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>Skills that the job possesses, selected from a predefinedlist.</description>
    <label>Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Aura Components</fullName>
            </value>
            <value>
                <fullName>Flows</fullName>
            </value>
            <value>
                <fullName>Permission Sets</fullName>
            </value>
            <value>
                <fullName>Reports and Dashboards</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Data Loader</fullName>
            </value>
            <value>
                <fullName>User Stories</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Agile Methodology</fullName>
            </value>
            <value>
                <fullName>Data Mapping</fullName>
            </value>
            <value>
                <fullName>Use Cases</fullName>
            </value>
            <value>
                <fullName>Wireframing</fullName>
            </value>
            <value>
                <fullName>Figma</fullName>
            </value>
            <value>
                <fullName>Design Tokens</fullName>
            </value>
            <value>
                <fullName>UX Writing</fullName>
            </value>
            <value>
                <fullName>Design System</fullName>
            </value>
            <value>
                <fullName>Security Review</fullName>
            </value>
            <value>
                <fullName>Integration Patterns</fullName>
            </value>
            <value>
                <fullName>Multi-Org Strategy</fullName>
            </value>
            <value>
                <fullName>System Scalability</fullName>
            </value>
            <value>
                <fullName>Data Modeling</fullName>
            </value>
            <value>
                <fullName>Shield Encryption</fullName>
            </value>
            <value>
                <fullName>Field Level Security</fullName>
            </value>
            <value>
                <fullName>Event Monitoring</fullName>
            </value>
            <value>
                <fullName>Audit Trail</fullName>
            </value>
            <value>
                <fullName>User Authentication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Service_MatchScoring.cls
public with sharing class Service_MatchScoring {
    public static DTO_ScoreResult calculateScore(Job__c job, Candidate__c candidate) {
        Integer matchScore = 0;
        
        Set<String> jobSkills = new Set<String>();
        Set<String> candidateSkills = new Set<String>();

        List<String> noNullishJobSkillsList = job.Skills__c != null ? job.Skills__c.split(';') : new List<String>();
        List<String> noNullishCandidateSkillsList = candidate.Skills__c != null ? candidate.Skills__c.split(';') : new List<String>();

        for(String jobSkill : noNullishJobSkillsList){
            jobSkills.add(jobSkill.trim());
        }

        for(String candidateSkill : noNullishCandidateSkillsList){
            candidateSkills.add(candidateSkill.trim());
        }

        for(String skill : jobSkills){
            if(candidateSkills.contains(skill)){
                matchScore += 20;
            }
        }

        if(matchScore == 0){
            return  new DTO_ScoreResult(matchScore, 'Sem match entre candidato e vaga');
        } else if(matchScore < 50){
            return new DTO_ScoreResult(matchScore, 'Match baixo entre candidato e vaga');
        } else if(matchScore >= 50 && matchScore <= 89){
            return new DTO_ScoreResult(matchScore, 'Match alto entre candidato e vaga');
        } else {
            return new DTO_ScoreResult(matchScore, 'Match perfeito entre candidato e vaga');
        }
    }
}